### ISSUE TITLE
smurf/Robot.hpp doesn't exist

### ISSUE THREAD

**Issue by jimaldon** [envire/envire-envire_smurf#2]
# include <smurf/Robot.hpp> in GraphLoader.hpp doesn't exist in gitlab:rock-dfki/smurf's master branch. It's in the envire_smurf branch.

**Comment by Rauldg** [comment]
The repository that you should be using for that one is the one from github. Somewhere an old override in your installation is checking out the wrong repository.

This is the right repo:
https://github.com/rock-cpp/smurf

**Comment by jimaldon** [comment]
Okay, thanks!
